excerpt_separator: ""
url: http://ywang-purdue.github.io/post_index.html
title: Hello World?!
email: ywang.chris@gmail.com
author: Yu Wang
description: Hello World?!
paginate: 30
google_analytics: 
